# **Assignment 1 For Numpy**

<div style='font-style:italic; font-size:24px'>
Student Name: Ali Raza Ali Qadri </br>
Roll No: PIAIC84325</br>
Batch: 7</br>
</div>

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
v1 = np.zeros(10)
v1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [3]:
v2= np.arange(10,49)
v2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

4. Find the shape of previous array in question 3

In [4]:
v2.shape

(39,)

5. Print the type of the previous array in question 3

In [5]:
print(type(v2))

<class 'numpy.ndarray'>


6. Print the numpy version and the configuration


In [6]:
print(np.__version__)

1.19.1


7. Print the dimension of the array in question 3


In [7]:
print(v2.ndim)

1


8. Create a boolean array with all the True values

In [8]:
True_value_arr = np.ones(5,dtype=bool)
True_value_arr

array([ True,  True,  True,  True,  True])

9. Create a two dimensional array




In [9]:
_2d_arr = np.arange(4).reshape(2,2)
_2d_arr

array([[0, 1],
       [2, 3]])

10. Create a three dimensional array



In [10]:
_3d_arr = np.arange(9).reshape(3,3)
_3d_arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
print(v2[::-1]) #v2 previously defined

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
v1[4]=1
print("Fifth value which is at index 4:",v1)

Fifth value which is at index 4: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [13]:
ident_matrix = np.identity(3)
ident_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [14]:
arr = np.array([1, 2, 3, 4, 5])
arr = arr.astype(float)
print("Array {0} \nArray Type: {1}".format(arr,type(arr)))

Array [1. 2. 3. 4. 5.] 
Array Type: <class 'numpy.ndarray'>


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [15]:
arr1 = np.array([[1., 2., 3.],
            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],
           [7., 2., 12.]])
mult_arr = np.multiply(arr1,arr2)
mult_arr

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [16]:
arr1 = np.array([[1., 2., 3.],
            [4., 5., 6.]]) 

arr2 = np.array([[0., 4., 1.],
            [7., 2., 12.]])
comp_arr = arr1 == arr2
comp_arr = comp_arr.all()
comp_arr

False

17. Extract all odd numbers from arr with values(0-9)

In [17]:
arr = np.arange(50)
print("Actual array: ",arr)
print("Extracted odd values: ",[i for i in arr if i>=0 and i<9 and i%2!=0])

Actual array:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
Extracted odd values:  [1, 3, 5, 7]


18. Replace all odd numbers to -1 from previous array

In [18]:
arr[arr%2!=0]*=-1
arr

array([  0,  -1,   2,  -3,   4,  -5,   6,  -7,   8,  -9,  10, -11,  12,
       -13,  14, -15,  16, -17,  18, -19,  20, -21,  22, -23,  24, -25,
        26, -27,  28, -29,  30, -31,  32, -33,  34, -35,  36, -37,  38,
       -39,  40, -41,  42, -43,  44, -45,  46, -47,  48, -49])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
arr = np.arange(10)
arr[5:9]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [20]:
arr_2d = np.ones((4,4))
print("Initial Array: ")
print(arr_2d)

arr_2d[1:-1,1:-1] = 0
print("\nAfter modifying: ")
print(arr_2d)

Initial Array: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

After modifying: 
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [21]:
arr2d = np.array([[1, 2, 3],
            [4, 5, 6], 

            [7, 8, 9]])

arr2d[1:2,1] = 12
print(arr2d)

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0][0] = 64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [23]:
arr1 = np.arange(4).reshape(2,2)
arr1_sliced = arr1[0:1]
arr1_sliced

array([[0, 1]])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [24]:
arr_2d = np.array([[0,1,2],
          [3,4,5],
          [6,7,8]])
print("2d Array:\n",arr_2d)
print("\n2nd Value from 2nd 1-D array = ",arr_2d[1:2,1])

2d Array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

2nd Value from 2nd 1-D array =  [4]


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [25]:
arr_2d = np.array([[0,1,2],
          [3,4,5],
          [6,7,8]])
print("2d Array:\n",arr_2d)
print("\n Third column but only the first two rows data = ",arr_2d[:2,2,])

2d Array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

 Third column but only the first two rows data =  [2 5]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
arr = np.random.random((10,10))

print("10x10 array with random values: \n",arr)

print("\nArray Max Value = {0}, Array Min Value = {1}".format(arr.max(),arr.min()))

10x10 array with random values: 
 [[0.16392721 0.08285903 0.82087489 0.46570228 0.43932701 0.56313308
  0.24937362 0.93999212 0.58898078 0.95745995]
 [0.841704   0.742399   0.33118428 0.38550864 0.39182634 0.88697134
  0.09109608 0.3365075  0.07055815 0.84466765]
 [0.89514948 0.69803855 0.32512088 0.31669561 0.89824349 0.29913483
  0.13007227 0.28601992 0.38615235 0.17026175]
 [0.02699734 0.41816936 0.88300741 0.55970327 0.57463139 0.45258925
  0.11041987 0.9929972  0.98011794 0.58194844]
 [0.62625737 0.07411389 0.41969565 0.46101275 0.48623142 0.70934872
  0.18674994 0.37668841 0.71044375 0.75121474]
 [0.91000161 0.26672034 0.39101064 0.705443   0.93397354 0.34177475
  0.25531397 0.93656022 0.25489901 0.60079352]
 [0.88502644 0.23444012 0.07059824 0.74172308 0.60422368 0.91458174
  0.77776019 0.51218037 0.30549856 0.27578463]
 [0.10185059 0.37887655 0.95823574 0.07709719 0.52686643 0.31186918
  0.49474559 0.83078011 0.25928387 0.2601277 ]
 [0.52599168 0.85767013 0.77344419 0.93530957 

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
common_elements = np.intersect1d(a,b)
print("Common Items are = ",common_elements)

Common Items are =  [2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])

print("Matching elements index: ",np.where(a == b))

Matching elements index:  (array([1, 3, 5, 7]),)


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [29]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print("Names: \n",names)
print("\nData: \n",data)
print("\nValues from array names are not equal to Will are: \n",data[names!='Will'])

Names: 
 ['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']

Data: 
 [[-0.42001249  0.42094274  0.51022632 -1.30914947]
 [ 0.51542088  0.77305014  0.11437425 -0.15787351]
 [-1.15742877  0.58343502  0.60362699  0.11745694]
 [-1.15034038  0.47418171  0.6246172  -0.81003793]
 [ 0.88022658  1.23506967 -0.77052308 -1.16418126]
 [ 0.54700502 -0.25057522  1.2505299  -0.69698862]
 [ 0.09469052  0.70852332  0.38971119 -0.48298095]]

Values from array names are not equal to Will are: 
 [[-0.42001249  0.42094274  0.51022632 -1.30914947]
 [ 0.51542088  0.77305014  0.11437425 -0.15787351]
 [-1.15034038  0.47418171  0.6246172  -0.81003793]
 [ 0.54700502 -0.25057522  1.2505299  -0.69698862]
 [ 0.09469052  0.70852332  0.38971119 -0.48298095]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [30]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print("Names: \n",names)
print("\nData: \n",data)

print("\nValues from array names are not equal to Will and Joe are: \n",data[(names != "Will") & (names != "Joe")])

Names: 
 ['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']

Data: 
 [[-0.74803465  1.43805221 -0.50670787  0.39117804]
 [-0.83858709  0.83653425 -0.28975681 -0.12848591]
 [-3.06988831  0.67145171  1.45640094  1.44665508]
 [-0.01274488 -0.13080419  0.8506288  -0.50862518]
 [-1.27034134 -1.29289785  0.85732966 -0.95616846]
 [ 0.21462048 -1.48005693  0.30903351 -0.18258308]
 [-1.30229028 -2.10231835 -1.26307015  0.99760811]]

Values from array names are not equal to Will and Joe are: 
 [[-0.74803465  1.43805221 -0.50670787  0.39117804]
 [-0.01274488 -0.13080419  0.8506288  -0.50862518]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [31]:
arr = np.random.uniform(1,15,size=(5,3))
print("Array: ",arr)
print('Array Shape: ',arr.shape)

Array:  [[ 7.84073534  4.73021195  8.58388973]
 [ 9.54186245  1.96106205  3.62982183]
 [12.35745844  6.29759601 10.05137556]
 [ 4.54345771 13.93391625 14.01855988]
 [ 8.96893766  5.70151591  7.91881003]]
Array Shape:  (5, 3)


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [32]:
arr = np.random.uniform(1,16,size=(2,2,4))
print("Array: ",arr)
print('Array Shape: ',arr.shape)

Array:  [[[14.09357787 10.91362014  1.67098097 12.09114818]
  [14.59706982 15.52591031  1.76359489 11.96544931]]

 [[ 5.07418682  1.86033079  2.02541085 15.27516601]
  [ 7.44075027  8.14998602  7.65156211 10.06967437]]]
Array Shape:  (2, 2, 4)


33. Swap axes of the array you created in Question 32

In [33]:
np.swapaxes(arr,1,2)

array([[[14.09357787, 14.59706982],
        [10.91362014, 15.52591031],
        [ 1.67098097,  1.76359489],
        [12.09114818, 11.96544931]],

       [[ 5.07418682,  7.44075027],
        [ 1.86033079,  8.14998602],
        [ 2.02541085,  7.65156211],
        [15.27516601, 10.06967437]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [34]:
from math import sqrt
arr=np.random.uniform(size=10)

print("\nBefore processing: \n",arr)

arr = np.array([sqrt(i) for i in arr])

arr[arr<0.5]=0

print("\nAfter processing: \n",arr)


Before processing: 
 [0.89855012 0.28123754 0.43529521 0.63966619 0.31045257 0.43557097
 0.86958288 0.93063557 0.83253238 0.97364896]

After processing: 
 [0.94791884 0.53031834 0.65976906 0.79979134 0.55718271 0.65997801
 0.93251428 0.96469455 0.91243212 0.98673652]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [35]:
arr1 = np.random.random(12)
arr2 = np.random.random(12)
print("\nArray 1: \n {0}\n \nArray 2: \n {1}\n".format(arr1,arr2))

max_val = np.array([arr1.max(),arr2.max()])

print("Max Values: ",max_val)

arr3 = np.random.uniform(max_val.max(),max_val.min(),size=(2,2))
print("\nArray between the max values\n",arr3)


Array 1: 
 [0.2357173  0.91391691 0.95225719 0.01663258 0.6738391  0.82369603
 0.7997363  0.05798079 0.92925758 0.85171398 0.31939563 0.30289189]
 
Array 2: 
 [0.72947905 0.95150357 0.57851398 0.76369617 0.36789595 0.10715021
 0.2263607  0.06845053 0.83491021 0.88008942 0.17066051 0.54225617]

Max Values:  [0.95225719 0.95150357]

Array between the max values
 [[0.95152097 0.95190649]
 [0.95185289 0.95215311]]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [36]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

unique_names = np.unique(names)
sorted_names = np.sort(unique_names)

print("Unique names: {0}\n\nSorted names: {1}".format(unique_names,sorted_names))

Unique names: ['Bob' 'Joe' 'Will']

Sorted names: ['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [37]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
c = np.setdiff1d(a,b)
print(c)



[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [38]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])

print("Before: \n",sampleArray)

sampleArray = np.delete(sampleArray,1,1)
print("\nAfter Deleting: \n",sampleArray)

sampleArray = np.insert(sampleArray,1,newColumn,axis=1)
print("\nAfter Inserting newColumn in 2nd column place: \n",sampleArray)

Before: 
 [[34 43 73]
 [82 22 12]
 [53 94 66]]

After Deleting: 
 [[34 73]
 [82 12]
 [53 66]]

After Inserting newColumn in 2nd column place: 
 [[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [39]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print("Dot Product:\n",np.dot(x,y))

Dot Product:
 [[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [40]:
matrix = np.random.rand(20)
print("Matrix: \n",matrix)

print("\nCumulative Sum = ",np.cumsum(matrix))

Matrix: 
 [0.21424642 0.21930056 0.73308066 0.43870859 0.73352188 0.12237468
 0.6967394  0.13945825 0.93431334 0.28425031 0.96341574 0.21317845
 0.47563227 0.51172624 0.86364363 0.81546593 0.21027317 0.75773527
 0.5045078  0.2566594 ]

Cumulative Sum =  [ 0.21424642  0.43354698  1.16662763  1.60533622  2.3388581   2.46123278
  3.15797217  3.29743042  4.23174376  4.51599407  5.47940981  5.69258826
  6.16822053  6.67994677  7.54359039  8.35905633  8.56932949  9.32706476
  9.83157256 10.08823196]
